apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matching-demo-app
  namespace: argocd
spec:
  project: default
  source:
    helm:
      values: |
        image:
          # @TODO: Update this when images are properly labelled on GCHR
          repository: ghcr.io/hostspaceng/origin247-apps-dockerfiles
          tag: main
        ingress:
          enabled: true
          annotations:
              kubernetes.io/ingress.class: nginx
          hosts:
            - host: matching-demo.devops-playground.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
    repoURL: https://github.com/energywebfoundation/generic-microservices-helm.git
    targetRevision: master
    path: ./
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
