apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: origin-247-redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: redis
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: git@github.com:Timtech4u/devops-playground.git
    targetRevision: HEAD
    ref: timtechRepo
  - repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 17.4.2
    helm:
      valueFiles:
        - $timtechRepo/training/values/origin-247/redis.yaml         
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
