server:
  service:
    type: LoadBalancer
#   persistentVolume:
#     volumeName: kubernetes-dynamic-pvc-vol-04e12907e21ffd6a3
alertmanager:
  persistentVolume:
    storageClass: gp2
server:
  persistentVolume:
    storageClass: gp2
