apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: git@github.com:Timtech4u/devops-playground.git
    targetRevision: HEAD
    ref: timtechRepo
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: HEAD
    helm:
      valueFiles:
        - $timtechRepo/argocd-apps/eks-apps/values/grafana.yaml         
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
