apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: helium-grafana
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helium-grafana
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL:  https://github.com/Techebraheem/Monitoring.git
    targetRevision: HEAD
    ref: techebraheemRepo
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 6.52.2
    helm:
      valueFiles:
        - $techbraheemRepo/argocd-apps/eks-apps/values/grafana.yaml         
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
