apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-deployment
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hola
  template:
    metadata:
      labels:
        app: hola
    spec:
      containers:
      - name: hola
        image: gcr.io/cloudrun/hello
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hola-service
  namespace: argocd
spec:
  selector:
    app: hola
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: NodePort
# status:
#   loadBalancer:
#     type: application
#     ingress:
#       - hostname: waf-alb-873823791.us-east-1.elb.amazonaws.com
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: hola-tgb
spec:
  serviceRef:
    name: hola-service
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:712726181972:targetgroup/waf-alb-target-group/3821bc97d59d50c7