apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Timtech4u/devops-playground.git
    targetRevision: main
    path: new-argocd-apps
  destination:
    name: in-cluster
    ### override by passing the below values in the child apps ###
    # server: https://kubernetes.default.svc
    # namespace: cert-manager
    
