### Cert-Manager (first step)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: default
spec:
  project: default
  source:
    helm:
      values: |
        installCRDs=true
    chart: jetstack/cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.9.1
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
---
### Cloudflare Origin CA Issuer (requires cert-manager)
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: cloudflare-origin-ca-issuer
#   namespace: default
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/cloudflare/origin-ca-issuer.git
#     targetRevision: trunk
#     path: deploy/charts/origin-ca-issuer
#   destination:
#     namespace: cert-manager
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: false
#     syncOptions:
#     - CreateNamespace=true
