## Cert-Manager (first step)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.9.1
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
    chart: cert-manager
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
## Cloudflare Origin CA Issuer (requires cert-manager)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-origin-ca-issuer
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/cloudflare/origin-ca-issuer.git
    targetRevision: trunk
    path: deploy/charts/origin-ca-issuer
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
---
# # issuer.yaml  (requires cert-manager)
# apiVersion: cert-manager.k8s.cloudflare.com/v1
# kind: OriginIssuer
# metadata:
#   name: prod-issuer
#   namespace: cert-manager
# spec:
#   requestType: OriginECC
#   auth:
#     serviceKeyRef:
#       name: origin-ca-key
#       key: key
