apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm: 
      parameters: 
        - name: image.repository
          value: dpregistryhs.azurecr.io/flask-app
        - name: image.tag
          value: c6a64e4a06084a54845c912d9e93bc889394262b
        - name: ingress.enabled
          value: true
        - name: ingress.className
          value: nginx
      values: |
        ingress:
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - host: devops-playground.timtechtu.dev
              paths:
                - path: /
                  pathType: Prefix
                  port: 8080
    repoURL: git@github.com:Timtech4u/devops-playground.git
    targetRevision: main
    path: ./Flask-App-HelmChart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
