apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |
        env:
          USERNAME: "timuser"
          PASWORD: "mgpassword"
        image:
          repository: dpregistryhs.azurecr.io/flask-app
          tag: c6a64e4a06084a54845c912d9e93bc889394262b
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - host: devops-playground.timtech4u.dev
              paths:
                - path: /
                  pathType: Prefix
                  port: 8080
    repoURL: git@github.com:Timtech4u/devops-playground.git
    targetRevision: main
    path: ./Flask-App-HelmChart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
