## KNative Operator Generated Helm Chart
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Timtech4u/devops-playground
    targetRevision: main
    path: knative-operator-helm
  destination:
    namespace: knative
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Additional Manifests for KNative Serving
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Timtech4u/devops-playground
    targetRevision: main
    path: knative/serving
  destination:
    server: https://kubernetes.default.svc
    namespace: knative
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      allowEmpty: true
      prune: true
      selfHeal: false
      