--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: nats-app
  namespace: default
spec: 
  destination: 
    namespace: nats
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    chart: bitnami/nats
    helm: 
      parameters: 
        - name: service.type
          value: LoadBalancer
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: "7.3.2"
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true
