apiVersion: v1
data:
  key: djEuMC1mZWE5MjZmNWVmYjNkNTEwNmQ2ZDgxZGYtMmE1MjMxOGJhYzAzZDBiMTAzY2Q1YWM3YTQ5NWJjN2Q3ZDI2NjQ5Mzc1NTU0Y2ViZTI4YTVjODBhMWZiODY5ZjRlYzM5YTczNmM3MzFiMjk5NWFhN2JkOWM0MDhjNmQzMmVmZjMwZDI0MTkyYzIxMmEzM2Y0NzljODk3MGVkZDQ3NDliNmQzMmRjM2EwOTdl
kind: Secret
metadata:
  creationTimestamp: null
  name: origin-ca-key
  namespace: cert-manager
