apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-app
  namespace: default
spec:
  destination:
    namespace: database
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
       - name: service.type
         value: "LoadBalancer"
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.6.15
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
