apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-blackbox-exporter
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 7.0.0
    helm:
      values: |
        targets:
          - name: probe-google                    # Human readable URL that will appear in Prometheus / AlertManager
            url: https://google.com  # The URL that blackbox will scrape
            labels: {}                       # Map of labels for ServiceMonitor. Overrides value set in `defaults`
            interval: 60s                    # Scraping interval. Overrides value set in `defaults`
            scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`
            module: http_2xx        
      parameters:
        - name: installCRDs
          value: 'true'
    chart: prometheus-blackbox-exporter
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
