apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: default
spec:
  project: default
  source:
    repoURL: https://energywebfoundation.github.io/generic-microservices-helm/
    targetRevision: 0.1.2
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/limit-rps: "5"
            # nginx.ingress.kubernetes.io/limit-rpm: "300"
            # nginx.ingress.kubernetes.io/rewrite-target: /
            nginx.ingress.kubernetes.io/server-snippet: |
              location = / {       
                proxy_pass http://grafana.monitoring.svc.cluster.local;
              }            
          hosts:
            - host: demo.devops-playground.com
              paths:
                - path: /
                  pathType: ImplementationSpecific        
        containerPort: 8080
        image:
          repository: gcr.io/cloudrun/hello
          tag: latest
    chart: microservice
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
