apiVersion: k8s.nginx.org/v1 
kind: Policy 
metadata: 
  name: rate-limit-policy 
spec: 
  rateLimit: 
    rate: 10r/s 
    key: ${binary_remote_addr} 
    zoneSize: 10M 
--- 
apiVersion: k8s.nginx.org/v1 
kind: VirtualServer 
metadata: 
  name: rate-virtual-server 
spec: 
  ingressClassName: nginx-api 
  host: limits.hostspaceng.com 
  policies: 
  - name: rate-limit-policy 
  upstreams: 
  - name: api 
    service: hello-service 
    port: 8000
  routes: 
  - path: / 
    action: 
      pass: api
