apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-locations
  namespace: argocd
spec:
  project: default
  source:
    helm:
      values: |
        env:
          BACKEND_URL: http://next-app-service.default.svc.cluster.local
          FRONTEND_URL: http://hello-service.default.svc.cluster.local      
        ingress:        
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/rewrite-target: /
            nginx.ingress.kubernetes.io/server-snippet: |
              server_name double-location.hostspaceng.com;

              location /hello {
                      proxy_pass http://hello-service.default.svc.cluster.local;
              }
              location /next {
                  proxy_pass http://next-app-service.default.svc.cluster.local;
              }
              error_page   500 502 503 504  /50x.html;
              location = /50x.html {
                      proxy_pass http://hello-service.default.svc.cluster.local;
              }           
    repoURL: https://github.com/energywebfoundation/generic-microservices-helm.git
    targetRevision: master
    path: ./
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
    
