apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-locations
  namespace: argocd
spec:
  project: default
  source:
    helm:
      values: |
        env:
          BACKEND_URL: http://next-app-service.default.svc.cluster.local
          FRONTEND_URL: http://hello-service.default.svc.cluster.local    
        ingress:
          enabled: true
          annotations:
              kubernetes.io/ingress.class: nginx
          hosts:
            - host: double-location.hostspaceng.com
              paths:
              - path: /hello
                pathType: Prefix
                backend:
                  service:
                    name: hello-service
                    port:
                      name: http
              - path: /next
                pathType: Prefix
                backend:
                  service:
                    name: next-app-service
                    port:
                      name: http                      
    repoURL: https://github.com/energywebfoundation/generic-microservices-helm.git
    targetRevision: master
    path: ./
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
    
