apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: nginx
data:
  enable-rate-limiting: "true"
  rate-limit-requests-per-second: "10"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rate-limiting-ingress
  annotations:
    nginx.ingress.kubernetes.io/limit-req-zone: "$binary_remote_addr zone=api"
    nginx.ingress.kubernetes.io/limit-req: "zone=api burst=5 nodelay"
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: limits.hostspaceng.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-service
                port:
                  name: http
  tls:
    - hosts:
      - limits.hostspaceng.com
