apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robusta
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |
        clusterName: playground
        globalConfig:
          signing_key: 8b912b36-7350-45cb-bf71-c82a68dbb6f0
          account_id: 64d35d36-d786-48fc-8c38-70b5b023d100
        sinksConfig:
        - slack_sink:
            name: main_slack_sink
            slack_channel: monitoring
            api_key: xoxb-4446357609872-4863613767655-bEBrzZe39s5CoPvSbI6aI2Wd
        - robusta_sink:
            name: robusta_ui_sink
            token: eyJhY2NvdW50X2lkIjogIjY0ZDM1ZDM2LWQ3ODYtNDhmYy04YzM4LTcwYjViMDIzZDEwMCIsICJhcGlfa2V5IjogImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUp5YjJ4bElqb2lZVzV2YmlJc0ltbGhkQ0k2TVRZeU5ERTNNalF5TkN3aVpYaHdJam94T1RNNU56UTROREkwZlEuaFJMdjZQQW54MWNhdkR3bC1pWXlnQXJINHFBMERWSFluckQ3MUFzcXFQdyIsICJzdG9yZV91cmwiOiAiaHR0cHM6Ly94dnlocG94Zm10cHVxcWV5cWtzby5zdXBhYmFzZS5jbyIsICJlbWFpbCI6ICJhcGl1c2VyLWhvc3RzcGFjZS0xMzIyNDZAcm9idXN0YS5kZXYiLCAicGFzc3dvcmQiOiAiY2M4OTBhMzAtODg1OC00MGJkLWFkODYtMzViMDUyZGY3YWJjIn0=
        enablePrometheusStack: true
        enablePlatformPlaybooks: true
        runner:
          sendAdditionalTelemetry: true
        rsa:
          private: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBc3BpRVJ6R1JodTBUTHVTR3pIbyt0QmtCUFpLYy93ZTBBS1BHU0t3R2k0SUZjT0lLCjY1S2pFcXNKMUtPRHJqYytXc2g0ZHNUUXlSbDE3dWxIQU8xN2VGdkg5OEU0L0FDWWlEWEIvSTVOeTdJeXVERVAKSXBLTUt5ckw0TmtFNml3MkQ4eUxDNTJDdjFwVTc5T1M2MWRnL3JDaDBDaFNCK2xreHVWVUIvRFVnOWxVVExlSApNODEzMStVTEFIaGhTMGJYcTkwMm14dU5jL3FNZk44L0FFelA4UkUyTGFlNWxyaWJ0Q1dvVFFKczliRDdZODVvCmlyQWVDQWNyUHJ6WkZaVWhuNlFQeFAxNVU5VkhEWXp2NDY1T1FnbmFtTWE5cGxEVUxJaG8rR09CN1VqRTV4UjEKWGNWaFd4aXlNQ2VsWSszb1NDTkY2Uy81RkNpaG5ucXlML2cxb3dJREFRQUJBb0lCQUJxNDgySHJxc2l6aEdGSgoxRm1ZR1BXOW9BL2tkaFU2dzlZc3F5aUloTm91OUQxMXRRaVdna3Z5eDUvSGI1YUxzWXJINEM1MU9JQStqUVRZClpzVmV3MUM0K3V5NVBwdUdRMHh1THI1cFZINmNCVGJHTUd1TjNlYy9tZzNrcXZXVzgrZmRSUmpSMHBSckliWlkKdyt6dXdCYWJ1enA0TGYzOUVCVXFqeTQ0L0xOVmV5a2hOaDBHZ21hQytIM3oyZnQyb0JiaW9YcDRnWnJJNzdYSgpjOEs1NC9reWNSM09laGNLN2tYS3R6R2E3MWtmcjBwTmtMcHV5Yys2ZmJUSVhEdE9PenRKeWd4OVBjUks1RFlLCmJldEUxZU9ZRnRsb1RQRHBTKzVEWisrSEJOd2VyaldCd0QzejJYR1I0T3l3VzNJYkJjeWI1SHFybTF5dkRIZUwKaU5Ya2ZBRUNnWUVBNllKN1J6bVd2Qjh4SDRySDFBa2I3cjFKejdJYlRoREJra1kxNDJDV1NMdHB4VHJ3Y2lpWgpET3NNdTZ1RnprK0lER0k0WllrQzRTL2w1ZGppMjMxaUthK2tVZmo5eE1FWnlTS1VpQzMyaFF1UXdtcVlSY2hzCnNEOG9uVmp6RTBJOHVLWVd0Z2pjVFJleWQrL0JkQmtIMFIvV0VDRzlmZUFObThBbkFvR01PUUVDZ1lFQXc4d04KbDJBclhhakxWbERFSWlLcTE5Ny9YbXhEd2NnaTA0RStWVTBzYUIxUDN6Y2dJQkw4TE40UHFDdlpBd0F6UXM3cQp4MVBFbjJpbHdBTkZrekY3OHJxTytwREJkZnRtOGl2MWJoWnk0d3dHUkVMaFNkWGxlZFE1a2dId3FEcXlZOElDCnFYWlRDUEsvZjY0UXFneUxXTXgzbEJ6NFAveUtUNVBmQ0ZxVjZxTUNnWUFPUnVzUXJNVzVsTktsRWhBcnQ2N2MKaHZoSFdhVnZ2WGlJWUFDVmVXZFc1UmFQZDQ0Ui9NZDIwYnhDa1RjcUtSU3haU1A3bVVmeXlzSHNycmtZSUc5cgpDeEVwN2VaZUxFeE9UdTN6OFpOOENQdjkxeFNlVjZYRmxPYi96OXQwMXZ6dGNVSThPUWgzTWphNFBKR0Fick5hCnB1Nm9wOWQxSmNqUE9BMXFpczh2QVFLQmdRQ25pK2loZmJEK1Q1L1l0L3B1UDM0MGhlVysxaVJSSWNMemZLaHIKZEVPb3dGU0Y3WFUzSFNmZitSSXExWUs1ZDZWbDZReXREemkxTkdhSjNnTGVoenpLbyt3UDdHa3dYYlpsUzBxVgpMdTZXN2NZN0NZUWhtOERudEx5aS9iZ0RMVjlUMEVSWTRTRURDajdtc253ZUYrZnlUOTJQeUE2REtzYnNlOXdpCkdPb3F3d0tCZ1FDd00wdnRSd0dTWFc0alluK29UbUtTRG1kZ0wxalh3TEJxT2Z4anM1aGZDaVdrd2FJZEVYQWIKS0RkWFlJbEVkNWZsVGNXK2RVZlVNUUpEY2IvN0l1L1VCZ21jRVNWNFlndDFnZEdoMkVYeFZ0YVNMOXE4YnVIaAp4SXlHR1dEMEJjSFdYUmZ5cmd4emlLcThDcExXQWFtTXJ2UGJtdXV4Y0EzTHJGdXdKUlM3R0E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
          public: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFzcGlFUnpHUmh1MFRMdVNHekhvKwp0QmtCUFpLYy93ZTBBS1BHU0t3R2k0SUZjT0lLNjVLakVxc0oxS09EcmpjK1dzaDRkc1RReVJsMTd1bEhBTzE3CmVGdkg5OEU0L0FDWWlEWEIvSTVOeTdJeXVERVBJcEtNS3lyTDROa0U2aXcyRDh5TEM1MkN2MXBVNzlPUzYxZGcKL3JDaDBDaFNCK2xreHVWVUIvRFVnOWxVVExlSE04MTMxK1VMQUhoaFMwYlhxOTAybXh1TmMvcU1mTjgvQUV6UAo4UkUyTGFlNWxyaWJ0Q1dvVFFKczliRDdZODVvaXJBZUNBY3JQcnpaRlpVaG42UVB4UDE1VTlWSERZenY0NjVPClFnbmFtTWE5cGxEVUxJaG8rR09CN1VqRTV4UjFYY1ZoV3hpeU1DZWxZKzNvU0NORjZTLzVGQ2lobm5xeUwvZzEKb3dJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==        
  repoURL: https://robusta-charts.storage.googleapis.com
  chart: robusta
  targetRevision: 0.10.12
  helm:
    valueFiles:
      - $timtechRepo/argocd-apps/nginx-manifests/values/robusta.yaml         
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
