apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-proxied-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-snippet: |
          server_name  host1.hostspaceng.com host2.hostspaceng.com;

          location /mail {
              proxy_pass http://my-mailhog.default.svc.cluster.local:8025;
          }
spec:
  rules:
    - host: static-cache.hostspaceng.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: next-app-service
                port:
                  name: http
          - path: /mailz
            pathType: Prefix
            backend:
              service:
                name: my-mailhog
                port:
                  number: 8025
