apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-proxied-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/mailhog)$ $1/ redirect;
      rewrite ^(/hello)$ $1/ redirect;
spec:
  rules:
    - host: static-cache.hostspaceng.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: next-app-service
                port:
                  name: http
          - path: /mailhog(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: my-mailhog
                port:
                  name: http
          - path: /hello(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: hello-service
                port:
                  name: http
