apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-balo-app
  namespace: argocd
spec:
  project: default
  source:
    helm:
      values: |
        image:
          repository: ghcr.io/energywebfoundation/matching-demo
          tag: "latest"       
        service:
          port: 5000          
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt-production
          hosts:
            - host: matching-demo-ui.hostspaceng.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: matching-demo-ui
              hosts:
                - matching-demo-ui.hostspaceng.com 
    repoURL: git@github.com:hostspaceng/helm-charts.git
    targetRevision: main
    path: ./
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
  
