apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: git@github.com:Timtech4u/devops-playground.git
    targetRevision: HEAD
    ref: timtechRepo
  - repoURL: https://helm.nginx.com/stable
    chart: nginx-ingress
    targetRevision: 0.13.2
    helm:
      valueFiles:
        - $timtechRepo/argocd-apps/rc-test/values/values-ingress-nginx.yaml         
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
