apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  annotations:
    nginx.ingress.kubernetes.io/limit-rate: "10r/h"
    nginx.ingress.kubernetes.io/server-snippet: |
    
      server_name aws-proxy.hostspaceng.com;
      
      location ~* {
          proxy_pass https://www.google.com;
          sub_filter google.com example.com;
          sub_filter_once off;
      }
spec:
  ingressClassName: nginx
  rules:
  - http:
    host: aws-proxy.hostspaceng.com
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guestbook-ui
            port:
              number: 80
