name: ArgoCD Create
on: workflow_dispatch
jobs:
  Create:
    runs-on: ubuntu-latest
    steps:
      - name: ArgoCD Login
        id: argocd_login
        uses: clowdhaus/argo-cd-action/@v1.12.1
        env:
          argocd_url: "argocd.devops-playground.com"
          argocd_username: "admin"
          argocd_password: "RiEBfS0BiF0uuBWk"
        with:
          command: login ${{ env.argocd_url }}
          options: --insecure --password ${{ env.argocd_password }} --username ${{ env.argocd_username }}

      - name: ArgoCD create app
        uses: clowdhaus/argo-cd-action/@v1.12.1
        env:
          name: "base"
          repo: "git@github.com:Timtech4u/devops-playground.git"
          path: "explore"
          dest-namespace: "default"
          dest-server: "https://kubernetes.default.svc"
          sync-policy: "auto" 
        with:
          command: app create ${{ env.name }}
          options: --repo ${{ env.repo }} --path ${{ env.path }} --dest-namespace ${{ env.dest-namespace }} --dest-server ${{ env.dest-server }} --sync-policy ${{ env.sync-policy }}
