# GitHub Actions workflow to deploy to Minikube

name: Minikube Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Minikube
      run: |
        minikube start --driver=docker
        kubectl apply -f celery
        kubectl apply -f django
        kubectl apply -f postgres
        kubectl apply -f redis
        kubectl get all
        minikube service list
        minikube service devops-playground-service --url

